name: Environment Setup

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      DEBUG: "true"
      MAX_CONNECTIONS: "200"
      TIMEOUT: "2.5"
      ENV_ID: "1a2b3c"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: bash ./setup_environment.sh
